name: 🐛 Bug report
description: Describe a problem or bug with LosslessCut
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first:
      options:
        - label: Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest):
          required: true
        - label: Read all the documentation at https://github.com/mifi/lossless-cut and **Known issues / Troubleshooting**
          required: true
        - label: Search for your problem under Issues or Discussions
          required: true
        - label: Try other type of file and see if it works.
          required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you running?
      options:
        - MacOS 12
        - MacOS 11
        - MacOS 10
        - Windows 11
        - Windows 10
        - Windows 8.1
        - Windows 8
        - Windows 7
        - Windows Vista
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How would I reproduce the problem? Please describe step-by-step what you're doing from starting up LosslessCut until the problem occurs. You can attach screenshot if needed.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What happens instead?
    validations:
      required: true
